baseURL = "/"
languageCode = "en-us"
title = "Riser Platform"
theme = "syna"
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/riser-platform/riser"
    weight = 3


[params]
  name = "Riser"
  description = "An opinionated app platform built on Kubernetes"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# old whysper params:
# [params]
#   homepage_button_link = '/docs'
#   homepage_button_text = 'Read The Docs'
#   homepage_intro = 'An opinionated app platform built on Kubernetes'

# [params.logo]
#   mobile = "/images/logo-mobile.svg"
#   standard  = "/images/logo.svg"